### ISSUE TITLE
S1 - Crear Wireframe Sala de joc

### ISSUE THREAD

**Issue by Luky7600** [aPelCinc/aPelCinc#6]

**Comment by KristhelC** [comment]
![image](https://user-images.githubusercontent.com/72143611/164255901-ac3e4158-8b7e-41d4-bc89-affb1045627b.png)

**Comment by nemesxv** [comment]
![imagen](https://user-images.githubusercontent.com/83652031/164482938-94a5578a-279f-41a6-a5fa-3f794d864bc1.png)
